  services:
    backend:
      build:
        context: ./backend
        dockerfile: Dockerfile
      image: denizhansan/todo-backend:v2
      container_name: todo-backend-container
      ports:
        - "8000:8000"
      env_file:
        - .env
      depends_on:
        - mongodb
      networks:
        - todo-network

    frontend:
      build:
        context: ./frontend
        dockerfile: Dockerfile
      image: denizhansan/todo-frontend:v3
      container_name: todo-frontend-container
      ports:
        - "5500:5500"
      depends_on:
        - backend
      networks:
        - todo-network

    mongodb:
      image: mongo
      container_name: todo-mongo
      restart: always
      ports:
        - "27017:27017"
      volumes:
        - mongo-data:/data/db
      environment:
        MONGO_INITDB_ROOT_USERNAME: admin
        MONGO_INITDB_ROOT_PASSWORD: password
      networks:
        - todo-network

    mongo-express:
      image: mongo-express
      container_name: todo-mongo-express
      restart: always
      ports:
        - "8081:8081"
      environment:
        ME_CONFIG_MONGODB_SERVER: mongodb
        ME_CONFIG_MONGODB_ADMINUSERNAME: admin
        ME_CONFIG_MONGODB_ADMINPASSWORD: password
      depends_on:
        - mongodb
      networks:
        - todo-network
    
    sonarqube:
      image: sonarqube:lts-community
      container_name: todo-sonarqube
      restart: always
      ports:
        - "9000:9000"
      environment:
        SONAR_JDBC_URL: jdbc:postgresql://postgres:5432/sonar
        SONAR_JDBC_USERNAME: sonar
        SONAR_JDBC_PASSWORD: sonar
      volumes:
        - sonarqube-data:/opt/sonarqube/data
        - sonarqube-logs:/opt/sonarqube/logs
        - sonarqube-extensions:/opt/sonarqube/extensions
      depends_on:
        - postgres
      networks:
        - todo-network

    postgres:
      image: postgres:17
      container_name: todo-postgres
      restart: always
      ports:
        - "5432:5432"
      volumes:
        - postgres-data:/var/lib/postgresql/data
      environment:
        POSTGRES_USER: sonar
        POSTGRES_PASSWORD: sonar
        POSTGRES_DB: sonar
      networks:
        - todo-network

  volumes:
    mongo-data:
    postgres-data:
    sonarqube-data:
    sonarqube-logs:
    sonarqube-extensions:

  networks:
    todo-network:
      external: true