  apiVersion: v1
  kind: Service

  metadata:
    name: {{ .Values.backend.service.name }}
    namespace: {{ .Values.namespace }}

  spec:
    type: NodePort

    selector:
      app: {{ .Values.backend.appLabels }}

    ports:
      - port: {{ .Values.backend.service.port | quote }}
        targetPort: {{ .Values.backend.service.targetPort | quote }}
        nodePort: {{ .Values.backend.service.nodePort | quote }}
