apiVersion: v1
kind: Service

metadata:
  name: {{ .Values.frontend.service.name }}
  namespace: {{ .Values.namespace }}

spec:
  type: NodePort
  
  selector:
    app: {{ .Values.frontend.appLabels }}

  ports:
    - port: {{ .Values.frontend.service.port | quote }}
      targetPort: {{ .Values.frontend.containerPort | quote }}
      nodePort: {{ .Values.frontend.nodePort | quote }}