apiVersion: v1
kind: Secret

metadata:
  name: todo-app-secret
  namespace: todo-app

type: Opaque

stringData:
  MONGO_INITDB_ROOT_USERNAME: admin
  MONGO_INITDB_ROOT_PASSWORD: password
  MONGODB_URI: mongodb://admin:password@mongodb-service:27017/todo-app?authSource=admin