apiVersion: v1
kind: Service

metadata:
  name: {{ .Values.mongodb.service.name }}
  namespace: {{ .Release.namespace }}

spec:
  clusterIP: None
  
  selector:
    app: {{ .Values.mongodb.appLabels }}

  ports:
    - port: {{ .Values.mongodb.service.port }}
      targetPort: {{ .Values.mongodb.service.targetPort }}